### ISSUE TITLE
-c none produces pointless \e[0m after every line

### ISSUE THREAD

**Issue by kilobyte** [hpjansson/chafa#1]
Even if ``-c none`` is specified, *chafa* outputs a color code (\e[0m) at the end of every line.  That's not only pointless (there are no attributes to turn off), but also makes it impossible to pipe *chafa*'s output.  (Well, I know where to find *ansi2txt* or *sed*, but...)

**Comment by hpjansson** [comment]
Thanks, looks like I broke it when I refactored the string builder. Fixed by 743f1e2.
