### ISSUE TITLE
Reading image data from stdin raises "Failed to open '-': Unknown file format" error on Windows build

### ISSUE THREAD

**Issue by TransparentLC** [hpjansson/chafa#100]
Just tried using `-` as input file and found this difference. It seems that Windows build can't treat `-` as "reading image data from stdin".

Tested on version 1.8.0 for WSL Ubuntu 22.04 installed by apt and version 1.12.3 for Windows downloaded from project homepage and I'm sure the image isn't corrupted.

```sh
curl "https://picsum.photos/id/128/30/20.webp" -L --output - | chafa -
```
![屏幕截图 2022-07-29 200459](https://user-images.githubusercontent.com/47057319/181758072-738580ea-918c-4f77-945e-2ad442ca8cd4.png)

![屏幕截图 2022-07-29 200509](https://user-images.githubusercontent.com/47057319/181758080-4c736de8-d160-4ea4-8bbd-552811e50598.png)

**Comment by hpjansson** [comment]
Hi, thanks for reporting this issue! I've verified that it happens here too (Win10 PowerShell + scoop), and am working on a fix.

**Comment by hpjansson** [comment]
All that was needed in this instance was to enable binary mode on stdin.

For my own future reference, Chris Wellons has a [very nice and up-to-date summary](https://nullprogram.com/blog/2021/12/30/) of things one can do to sort of paper over the worst issues of the Windows platform.

There may be other Windows-specific bugs. If you find any more, I'd love to hear about them.
