### ISSUE TITLE
add display for multiple images horizontally

### ISSUE THREAD

**Issue by acxz** [hpjansson/chafa#102]
Having the ability to display multiple images in a horizontal fashion.

Right now calling multiple images with chafa defaults to a vertical layout, but it would be nice to also have a horizontal layout.

For reference, timg achieves this with the `--grid` flag. https://github.com/hzeller/timg/blob/cfd5f7a99401074ccfad31fa6234e94e5175074f/README.md?plain=1#L82

P.S. as a workaround currently I am using imagemagick to manually stitch the images together and then using chafa. I imagine if this step is done inside of chafa, the overall pipeline will be faster.

**Comment by hpjansson** [comment]
Absolutely. It's not even that hard to add, so I could see it making the 1.14 release.

For reference, I imagine you're using something like this...

```bash
montage -tile 6x -background none -geometry 64x64+1+1 *.png - | chafa -s 80
```

...which is indeed very slow, and also consumes lots of memory if it's a big collection. With proper support in `chafa`, you could also show file names etc.

**Comment by hpjansson** [comment]
This reminds me I also want something like a `--fit-width` switch or some other way to respect one terminal dimension while ignoring the other (as you would with tall images that're supposed to scroll vertically).

**Comment by acxz** [comment]
For images I am using `+append`:

https://github.com/acxz/pokeshell/blob/52b3ec29dfb9cb9e0c3a0ed4198d9c019536e84a/bin/pokeshell#L446-L447

However, for gifs I have to do something a bit more creative:
https://github.com/acxz/pokeshell/blob/52b3ec29dfb9cb9e0c3a0ed4198d9c019536e84a/bin/pokeshell#L524-L529

**Comment by clort81** [comment]
to fit width i just alias or script -s $(tput cols)

**Comment by wabiloo** [comment]
Any feedback on how I could do this?
And ideally I'm after a method that would work with the various pixel types...

**Comment by hpjansson** [comment]
Hi - I didn't have time to add this in 1.14, but I'll see if we can't get something going for 1.16. `--fit-width` is in now, though. Thanks for the interest.

**Comment by hpjansson** [comment]
It's done, feel free to test the new `--grid` argument on the master branch.
