### ISSUE TITLE
`--fg-only` doesn't reset text color

### ISSUE THREAD

**Issue by CairnThePerson** [hpjansson/chafa#105]
When using a shell prompt that doesn't specify color, it seems like `--fg-only` doesn't reset color after displaying an image. My shell, and any command that doesn't specify color, retains the last color used by Chafa.

![2022-08-27-011227_scrot](https://user-images.githubusercontent.com/73193674/187015950-0edb75be-66eb-4e53-b698-efa4811b706a.png)

**Comment by hpjansson** [comment]
Hi, that's correct. Other modes issue a `ESC[0m` after the image, but that resets the background color and attributes too. `--fg-only` isn't allowed to touch those, so it doesn't issue a reset.

This can be improved by issuing `ESC[39m` to reset the foreground color only. I'm not 100% sure where that escape code originated and how widely supported it is, though.

**Comment by CairnThePerson** [comment]
Ah, I see. Maybe better not to use a potentially unsupported escape code then?

**Comment by hpjansson** [comment]
We'll see, I'll research it a bit (would accept help here :-). I'm optimistic.

Is it possible for you to work around it in the meantime by issuing the escape at the beginning of your prompt?

**Comment by CairnThePerson** [comment]
Yeah, not a problem to work around. I was mainly sending the issue to make sure the program can be refined. =)

This is pretty far out of my understanding, but I'll take a look at it tonight to see if I can offer a suggestion. Thanks!

**Comment by hpjansson** [comment]
These are in ECMA 48 3rd ed, according to [a reliable source](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_). Search for `CSI Pm m  Character Attributes (SGR)`.

Also see [ECMA 48 3rd ed](https://www.ecma-international.org/wp-content/uploads/ECMA-48_3rd_edition_march_1984.pdf). section 8.2.71. This edition came out in 1985.

It works in kitty, screen, tmux, urxvt, VTE and xterm.

Seems good enough :-) I'll add the sequences.

**Comment by CairnThePerson** [comment]
Wow, fantastic!
