### ISSUE TITLE
for window !!

### ISSUE THREAD

**Issue by omaru-ok** [hpjansson/chafa#106]
i know it sound weird but can u make it for window ? :D

**Comment by hpjansson** [comment]
Hi! If you mean Microsoft Windows, there is already a binary for it here: https://hpjansson.org/chafa/download/ You will have to run it from PowerShell or cmd.exe on Windows 10 or newer.

If you mean a windowed app with a graphical UI, that's a much bigger ask and a little out of scope for this repository. Could be a fun project, though :-)

**Comment by omaru-ok** [comment]
but thx tho :D

**Comment by hpjansson** [comment]
No problem, feel free to bring up any issues you notice.
