### ISSUE TITLE
Progress b0rked our terminal welcome screen 😄

### ISSUE THREAD

**Issue by eMPee584** [hpjansson/chafa#108]
`chafa --colors 16 --size $(tput cols)x18 --color-space din99d --fill braille --work 3 -- /usr/local/share/icons/keine-panik.svg | lolcat` with chafa 1.6.0-1:
![Screenshot_20220828_044246](https://user-images.githubusercontent.com/1227833/187055370-98fae629-317d-4e9b-a79a-7f0dd0d0998a.png)

and with 1.12.1-1:
![Screenshot_2022-08-28_04-45-56](https://user-images.githubusercontent.com/1227833/187055401-1fb060dc-9871-423c-88c1-6a8d9b5cfe3c.png)

now fixed it with `chafa --colors 2 --size $(tput cols)x18 --color-space din99d -- /usr/local/share/icons/keine-panik.svg | lolcat` to be like this:
![image](https://user-images.githubusercontent.com/1227833/189227920-9d8fb987-eef6-4b93-b4bb-ba172e78d0e1.png)
which is not bad, but still, i liked the white lettering fill better 😄
Maybe you have an idea what changed about the conversion algorithm and whether there could be an option to get something similiar to the original effect.

This is the SVG used:
![keine-panik](https://user-images.githubusercontent.com/1227833/187055296-5ce6f7c1-526b-459a-8fe8-a91ce4ff09f4.svg)

**Comment by hpjansson** [comment]
Interesting challenge :-)

There were several big changes between 1.6 and 1.12, so I'll have to fiddle with it a bit and look at the interactions with lolcat before I can give a good answer.

Thinking out loud -- you may be able to get part of the way there by specifying `-O 0` to make lolcat happier and increasing the transparency threshold (e.g. `-t .9`) to get more fuzz on the edges. Maybe also increase work factor a little (`-w 5` or higher). You may also be able to get rid of some of the horizontal dotted line segments by applying `--symbols -border` (note the minus sign).

**Comment by hpjansson** [comment]
Quick workaround: `chafa --color-space din99d -c 16 -w 3 -t 1 --fill braille keine-panik.svg`. The `-t 1` does most of the work. I still need to figure out what exactly is confusing lolcat.

**Comment by eMPee584** [comment]
ha super cool that brings more white back
i guess doing away with the grey is tricky 😅
but it's nice as it is thanks 😎
![image](https://user-images.githubusercontent.com/1227833/190829400-36a709a2-6553-4056-af47-650ce654fcee.png)

**Comment by hpjansson** [comment]
This was actually caused by lolcat not handling inverted colors properly. I committed a fix to minimize the runs of inverted colors when possible.
