### ISSUE TITLE
Support SVG in static builds

### ISSUE THREAD

**Issue by hpjansson** [hpjansson/chafa#109]
Split from issue 88. See [comment](https://github.com/hpjansson/chafa/issues/88#issuecomment-1245409346) by @crmabs there.

I had to leave out SVG support from the static exes because it was hard to support in a static build. This has probably gotten easier in the past year or two.

We depend on a post-Rust-rewrite librsvg2. MXE still has the last C-only version, probably because they can't support a Rust toolchain either. I could probably add an option to use an older API, but old librsvg2 versions don't receive updates, so are probably insecure.

**Comment by hpjansson** [comment]
The static binaries for 1.14.0 have SVG support! Attn: @crmabs

**Comment by crmabs** [comment]
fantastic, thanks for your efforts! good to see progress.
 I was able to bridge the gap with a simple svg to bitmap program on windows which now can be removed.
 Other than that the whole idea works perfect so far. But the crown jewel is when you do the whole thing in kitty.
