### ISSUE TITLE
Not rendering with `--format=kitty` in terminal that has Kitty Image Protocol

### ISSUE THREAD

**Issue by latipun7** [hpjansson/chafa#114]
[WezTerm has support](https://github.com/wez/wezterm/issues/986) of Kitty Graphics Protocol. But, chafa didn't render anything when using `-f kitty`.
![image](https://user-images.githubusercontent.com/20012970/200166631-1becbc9a-a656-4ebe-b8ab-9ab1b9866b1a.png)

On the other hand, I tested [broot](https://github.com/Canop/broot#preview-files) which mention can display image in terminal that has Kitty Graphics Protocol, i.e. WezTerm, and its really can display image out of the box in WezTerm.

**Comment by cdluminate** [comment]
I can reproduce this problem in WezTerm. But WezTerm also supports `sixel` format which works well.

**Comment by latipun7** [comment]
Yeah, but this is still a bug worth mentioning, I didn't know other terminal implementing kitty graphics protocol other than wezterm & kitty has this issue.
Also, wezterm `sixel` still experimental according to its documentation (but already good).

**Comment by hpjansson** [comment]
Interesting. I don't have a clue what's causing it yet. Could be WezTerm is picky somehow.

**Comment by AnonymouX47** [comment]
Wezterm suppprt for the kitty graphics protocol is still experimental and from my experience, highly non-conformant/incomplete. See https://github.com/wez/wezterm/issues/986#issuecomment-1120622597 for *a few* cases amongst others.

**Comment by hpjansson** [comment]
Thanks for confirming this. We already default to sixels on WezTerm, so it's not a huge problem. I think if we were to solve this bug, it would have to be some kind of workaround for users who want to force Kitty-style output.

**Comment by AnonymouX47** [comment]
You're welcome.

> We already default to sixels on WezTerm

Oh, great.

**Comment by latipun7** [comment]
WezTerm tracked this in https://github.com/wez/wezterm/issues/2716 and fixed it in https://github.com/wez/wezterm/commit/2d255c2d758f8f6f7e17d0204d402599d01640de. Already test this with `chafa -c full -f kitty /path/to/img`. It's work for regular image or animated gif.

As this thread originally opened because I can't run `-f kitty` on wezterm, I would close this as resolved. Thank you ✨

**Comment by hpjansson** [comment]
Sweet, thanks for checking.
