### ISSUE TITLE
make appimage format

### ISSUE THREAD

**Issue by newyorkthink** [hpjansson/chafa#117]
or like viu nvtop, they make appimage format

appimage format it can run everywhere

not jus apt-get

**Comment by newyorkthink** [comment]
![image](https://user-images.githubusercontent.com/87791643/215649761-bc4d3220-4e68-4d8a-9687-ec363f44e8b9.png)

**Comment by newyorkthink** [comment]
![image](https://user-images.githubusercontent.com/87791643/215649877-d5a234c7-a808-481a-8543-8af6b19b994a.png)

**Comment by newyorkthink** [comment]
it  work

**Comment by hpjansson** [comment]
Sweet, thank you! Did you make the AppImage available somewhere, or the build files?

**Comment by newyorkthink** [comment]
I think your build static file is good.

**Comment by newyorkthink** [comment]
yes i make the appimage file, but is some big size --> 47MB, so, i think your build the static binary is OK, very good :)

like fzf , and bat , and other

**Comment by hpjansson** [comment]
Ok, thanks for trying it out.
