### ISSUE TITLE
when trying to open .mp4 files on wsl2 and osx terminal i get error ```2805 ◯  chafa output.mp4 chafa: Failed to open 'output.mp4': Unknown file format```

### ISSUE THREAD

**Issue by gschian0** [hpjansson/chafa#118]
when trying to open up .mp4 on mac terminal and windows wsl terminal
 I get unknown file format... 
on the remote ubuntu linux server it runs fine with the basic install... 
```2805 ◯  chafa output.mp4
chafa: Failed to open 'output.mp4': Unknown file format```

**Comment by hpjansson** [comment]
Hi, thanks for reporting the issue. Chafa does not officially support MP4 video playback, but some builds use ImageMagick as a fallback. ImageMagick supports video streams in some configurations but not others.

You either have a Chafa build without ImageMagick support, or an ImageMagick build without MP4 video support.

Video format support is planned for a future Chafa release -- in the meantime you can work around this by transcoding the video to a (large!) GIF or WEBP animation.

**Comment by gschian0** [comment]
from the page itself 
"You need the GLib and ImageMagick development files in order to perform the build. These are usually available from your package manager."
once I installed these... and reinstalled from the git link... still doesn't work on wsl2... but works great on the server.

**Comment by gschian0** [comment]
well.. for some reason it worked... then it stopped ... now I"m having trouble figuring out how I configured it again...

**Comment by gschian0** [comment]
I'm seeing this error ... ```chafa: Error loading 'frac.mp4': delegate failed `'ffmpeg' -nostdin -v -1 -i '%i' -vframes %S -vcodec pam -an -f rawvideo -y '%u.pam' 2> '%u'' @ error/delegate.c/InvokeDelegate/1966```

**Comment by hpjansson** [comment]
@gschian0 Ping -- did you check if `ffmpeg` is installed and has the required codecs?

**Comment by hpjansson** [comment]
@gschian0 Ping :-)
