### ISSUE TITLE
feature request: provide a way of excluding specific characters

### ISSUE THREAD

**Issue by cpackham** [hpjansson/chafa#120]
I'm using chafa to produce ascii art from various logos for use on embedded devices. Sometimes this ends up interfering with automated tests that screen scrape and detect `#`, `$` and `>` as prompt indicators.

I know I can exclude symbol classes with `--symbols -dot` but is it possible to exclude only specific characters (e.g. `--symbols -$ -# ->`, bash quoting issues aside).

**Comment by hpjansson** [comment]
Yes, you can do this using Unicode hexadecimal codes for the characters you want to exclude. For #, $ and > that's the same as ASCII codes:

`--symbols -23-24-3e` should do the trick.

I want to add a way to do this with lists of plain characters in brackets, e.g. `--symbols -[#$>]`. Let's keep this issue open for that.

**Comment by clort81** [comment]
![chineseOpera](https://user-images.githubusercontent.com/51511737/215283327-96515402-7dab-4502-9990-0325b16ceca7.png)
![grasses](https://user-images.githubusercontent.com/51511737/215283343-d08e8895-a544-44b3-89fd-a36035711b5a.png)
excluding ranges works, it's a bit of effort...

**Comment by clort81** [comment]
isn't this closeable? use the --symbols flag and add the unicode codepoints or ranges you want to exclude.

Here's an example:
```
--symbols bad+diagonal+ue080..ufd7b-ue1ed-u2683-u25a4-u2610-uECD5-u25b3-u21e6-ue84d-u0425-u0432-ue781-ue840-uecce-u0430-u041d-u2662-u255c-u207f-u25e0-uec07-u2265-u0420-u25c5-u263a-u0434-ue846-ue462-ue472-ue4d7-ue1d1-ue1e1-ue49d-ue49b-ue4a8-ue721-ue1d6-u25db-ue70c-u2025-u25ad-u222a-u25a1
```

**Comment by hpjansson** [comment]
I still haven't implemented the parsing that would let you do `--symbols [abcdæøå]`. Will close when that's done. Shouldn't be too long :-)
