### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by umop3plsdn** [hpjansson/chafa#121]
Wanted to try chafa out went to build it and it failed seems like its just doc stuff though is there a way to bypass?

I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/html/onechunk.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/onechunk.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/html/onechunk.xsl
make[2]: *** [Makefile:629: chafa.html] Error 4
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:626: chafa.1] Error 4
make[2]: Leaving directory '/home/da5id/chafa/docs'
make[1]: *** [Makefile:496: all-recursive] Error 1
make[1]: Leaving directory '/home/da5id/chafa'
make: *** [Makefile:405: all] Error 2

**Comment by hpjansson** [comment]
Try `./autogen.sh --disable-gtk-doc --disable-man`. If that doesn't work, you can edit the toplevel Makefile.am and remove the `docs` subdir, i.e:

`SUBDIRS = chafa libnsgif lodepng tools tests`

**Comment by hpjansson** [comment]
Were you able to build it in the end? It looks like the underlying problem is with your Docbook tools, or a temporary issue with the XSL loaded from the network.

**Comment by hpjansson** [comment]
@umop3plsdn Ping -- any luck?
