### ISSUE TITLE
Chafa fills up whole viewport for smaller images, when using sixel output format

### ISSUE THREAD

**Issue by Utkarsh-khambra** [hpjansson/chafa#122]
Steps to reporduce:
1. get a small image file (for example `convert -size 256x160 canvas:khaki png:img`)
2. run `chafa <image-file>`

Expected Behavior:
Chafa draws image of correct size.

Current behaviour:
Chafa fillup the whole view port.

Example image to use.
![force](https://user-images.githubusercontent.com/29328319/208235088-282c2ef2-2ff1-4575-85c4-0921ce632870.png)

When I draw this image I get this result.
![Screenshot from 2022-12-17 14-56-16](https://user-images.githubusercontent.com/29328319/208235330-4feb22d2-e2f1-4ccc-ad57-0c29185e434f.png)

**Comment by Utkarsh-khambra** [comment]
Tested on terminal contour, Konsole and foot

**Comment by hpjansson** [comment]
Hi, thanks for filing the issue. This should be working fine in recent releases. What's the output from `chafa --version`?

**Comment by Utkarsh-khambra** [comment]
Just checked it's working fine on master. Thanks

**Comment by hpjansson** [comment]
Ah, yes. That's a bit old. This was fixed in 1.12.0, although it's not perfect yet. See #119 for more.

Ask your friendly Fedora maintainer to update their package :-)
