### ISSUE TITLE
Chafa still not limiting to *only* glyphs defined in  --glyph-file

### ISSUE THREAD

**Issue by clort81** [hpjansson/chafa#135]
Updated to git master 2023-03-07 - still not able to define a set of codepoints for chafa to use.

I've created a .pcf consisting of only glyphs i want to use for matching: blapetscii-12.pcf.gz
These are a subset of identical glyphs at the same codepoints in my BlapinusE terminal font

Problem: Chafa returns codepoints not in the glyph file: yielding 'blank boxes'.

 /usr/local/bin/chafa --color-space=din99d --color-extractor=median  --symbols all --glyph-file /usr/share/fonts/X11/misc/blapetscii-12.pcf.gz -w 8 -s 80 shine-hoodlum.png
![chafa_badmatches](https://user-images.githubusercontent.com/51511737/223621870-444a9e9f-62b9-44dd-bbb2-797fa9774c0e.png)

If I do not specify -symbols all, chafa ignores the PUA range, despite these being in my glyph file.  But it also returns matches not in my glyph file.
![chafa_bad_atches_under_1ffff](https://user-images.githubusercontent.com/51511737/223622534-b842b0b1-bf80-4ec9-9627-d10ff061317c.png)
For example:
U+2509 ┉
U+2514 └
Do not appear in my glyph-file.

There still seems to be some program logic overriding my indicated preference for codepoints to use
----------------------------------------
Perhaps the simplest way to give user full control is provide a commandline parameter instructing chafa to read a textfile consisting of codepoints and codepoint-ranges to  *use*.  That is, use *exclusively*, not in addition to any hidden default ranges.  
The simplest textfile format to parse would be a carriage return delimited list of individual codepoints, or codepoint ranges indicated by "..".
```
2509
2514
E000..E07F
E7B6..E833
EB4D
EB54
```
When the user species a codepoint list, chafa would *not* use *any* codepoint not in the list.  

Attached is the current version of Blapinus 6x12 pcf font, and the blapetscii pcf font used for a template.  As well as the sample image to generate the error.

[BlapinusEMedium-12.pcf.gz](https://github.com/hpjansson/chafa/files/10917293/BlapinusEMedium-12.pcf.gz)
[blapetscii-12.pcf.gz](https://github.com/hpjansson/chafa/files/10917546/blapetscii-12.pcf.gz)

[shine-hoodlum.png.gz](https://github.com/hpjansson/chafa/files/10917365/shine-hoodlum.png.gz)
Original Art by 'Shine': https://csdb.dk/release/?id=219497

[EDIT] Other chafa users might find this perl script useful. It returns the codepoints of characters piped to it
```
perl -C7 -ne 'for(split(//)){print sprintf("U+%04X", ord)." ".$_."\n"}'
```
if you make it an alias or bash script named 'uc', you can quickly
$ echo [paste glyphs] | uc 
And get the codepoints for whatever you pasted.

[EDIT2] Some people are still doing *gorgeous* PETSCII in 2023!
https://csdb.dk/release/viewpic.php?id=229352&zoom=1

**Comment by hpjansson** [comment]
Correct, the glyph limitation code is not yet done. Also yes, I think being able to list codepoints would make sense as part of the "presets" feature I'm planning. Then you could specify palette colors, default screen size, etc. too and give the whole thing a name so it can be used repeatedly.

Sorry I haven't been as active lately, I'm working on a big feature chunk behind the scenes (new Smolscale that can composite on a background for pixel perfect sixel etc), plus day job fun and a week+ of the flu (actual flu flu, how about that).

**Comment by hpjansson** [comment]
Hmmm, I don't see `--symbols imported` anywhere in the command lines above, by the way. Does it help if you add that?

**Comment by clort81** [comment]
Thank you hpjansson for the reminder. I see i had forgotten to include --symbols imported+....

Sorry and thanks again.
