### ISSUE TITLE
The "--duration" option is not working well for still images

### ISSUE THREAD

**Issue by Delgan** [hpjansson/chafa#144]
Hi.

Basically, this will return immediately instead of waiting forever:
```
chafa -d inf foo.jpg
```

There is an overflow here as `interruptible_usleep` expects an `int`: https://github.com/hpjansson/chafa/blob/49a0bdee3fe7d345d5674ce7f6c13d17d648e53d/tools/chafa/chafa.c#L2187-L2190

**Comment by hpjansson** [comment]
Good catch!
