### ISSUE TITLE
broken linking with libwebp-1.3.1

### ISSUE THREAD

**Issue by vcunat** [hpjansson/chafa#152]
libwebp 1.3.1 changed their .pc files: https://github.com/webmproject/libwebp/commit/31c28db53c6fa3be7026212fdd1526280e3f0f52

and as a result chafa will fail, unless e.g. `-lwebp` flag is supplied manually.
Examples:
  - https://github.com/NixOS/nixpkgs/pull/240893#issuecomment-1635347507
  - https://bugs.gentoo.org/909429

**Comment by hpjansson** [comment]
Hey, thanks for reporting this! Seems like a quick fix, but I'm a bit device challenged today so it'll have to wait till I'm back in the bat cave; tomorrow or monday.

**Comment by vcunat** [comment]
No need to hurry, from my point of view.  We fixup it in distro(s) like this for now, but I thought it would be nice to have a proper released fix at some point in future.
