### ISSUE TITLE
Incorrect libwebp linking

### ISSUE THREAD

**Issue by tranzystorek-io** [hpjansson/chafa#153]
When testing a build for Void Linux, chafa 1.12.4 and 1.12.5 fail to find the `WebPGetInfo` symbol. This seems to be caused by configure.ac only looking for `libwebpdemux`, while that symbol is in the `libwebp` shared library.

**Comment by tranzystorek-io** [comment]
Nevermind, found the fix on main, sorry!

**Comment by hpjansson** [comment]
No problem. The fix will be in the next release, but it's a big one and still a few weeks out at least.
