### ISSUE TITLE
Remove ImageMagick support

### ISSUE THREAD

**Issue by hpjansson** [hpjansson/chafa#157]
ImageMagick is a complex dependency that's hard to support. While it's an extremely versatile library, it's also got a kitchen sink approach that includes spawning external processes, causing inadvertent resource exhaustion and security issues. It would be nice to remove this dependency to cut down on risk/maintenance/packaging footprint.

That would leave the `chafa` CLI tool with support for the following formats: GIF, JPEG, PNG, SVG, TIFF, WebP, XWD. We may want to add support for AVIF as mentioned in #98 first. Potentially other important image formats too (suggestions welcome).

We'd lose support for formats like PDF (which many distributions disable anyway) and all video transcoding via IM (ew!). Users who want to keep using these can pipe to stdin like in the following examples:

```bash
ffmpeg -i https://i.imgur.com/sa1Tz6q.mp4 -f gif - | chafa -d inf
```

```bash
convert https://oig.nasa.gov/docs/IG-21-025.pdf[0] gif:- | chafa -t 1 --bg white
```

...and the performance will be better too.

**Comment by jerch** [comment]
[QOI](https://qoiformat.org/) might be worth a look. It is not widespread as exchange format, but quite popular as internal image format in many apps. It has okish compression and is really fast for its small code footprint.

**Comment by hpjansson** [comment]
That would be nice to have, indeed. Since it's so little code, it would be easy to audit and fuzz test too.

**Comment by hpjansson** [comment]
AVIF and QOI support added, ImageMagick removed.
