### ISSUE TITLE
Artsy Chafa Output (Not Intended)

### ISSUE THREAD

**Issue by jcdw99** [hpjansson/chafa#161]
Chafa currently outputs the following for me:

![Screenshot 2023-08-22 at 11 50 34 AM](https://github.com/hpjansson/chafa/assets/75687879/d081a275-6bde-4f3e-8f82-697745244dea)

Although the output is interesting, it is absolutely not as intended. Is this a known issue, or is this a result of me using the library incorrectly?

Input are `.png` images.

**Comment by hpjansson** [comment]
Hi, thanks for filing this.

I can't comment on the artistic merit of this particular work of art, but there could be several things going on. It's hard to say without a little more information, though:

- Which terminal are you using?
- What's the output from `chafa --version`?
- Could you attach a sample `png` image I can test with?

**Comment by hpjansson** [comment]
Missed that you're using the library. Do you have a code snippet?

**Comment by hpjansson** [comment]
@jcdw99 I guess you're busy, but if you still want this fixed, these two pieces of information may be enough:

- Output from `echo $TERM`
- The name of your terminal, and if you're running inside screen or tmux.

It *looks* like Chafa is emitting more colors than the terminal understands (it's only rendering 16). So a workaround may be to use `chafa -c 16`.

**Comment by hpjansson** [comment]
The extra info is still needed in order to fix this issue. In the meantime, I just released version 1.14.0; maybe that one works better?

**Comment by hpjansson** [comment]
Since it's been a year with no response, I'm taking the liberty of closing the issue. Newer Chafa versions have a lot of improvements. Feel free to reopen if the problem persists.
