### ISSUE TITLE
--glyph-files doesn't play nice with Kreative Square's PUA

### ISSUE THREAD

**Issue by oshaboy** [hpjansson/chafa#167]
[Kreative Square](https://www.kreativekorp.com/software/fonts/ksquare/) has sixels in the PUA (F280-F2BF) rendered in a font but I can't get it working. I know it's quite an overly specific issue but Kreative Square and Chafa seem to be a match made in Heaven. 

The command I've tried was `chafa  --symbols F280..F2BF  --glyph-file KreativeSquare.ttf {Image File}`

**Comment by hpjansson** [comment]
That's a sweet font!

I suspect the following is happening: Terminals are inherently monospace, so the font symbols are set in cells that are all the same size (well, 8x8 plus 16x8 for fullwidth). Since the sixel symbols are tall and narrow they cover very little of the cell, so the algorithm can't use them effectively.

`chafa` has a secret debug option, `--dump-glyph-file <file>`, that lets you see what it thinks the glyphs look like. Here are some of the sixel glyphs from Kreative Square:

```c
    {
        /* [] */
        CHAFA_SYMBOL_TAG_,
        0xf281,
        CHAFA_SYMBOL_OUTLINE_8X8 (
            "        "
            "   X    "
            "        "
            "        "
            "        "
            "        "
            "        "
            "        ")
    },
    {
        /* [] */
        CHAFA_SYMBOL_TAG_,
        0xf282,
        CHAFA_SYMBOL_OUTLINE_8X8 (
            "        "
            "        "
            "   X    "
            "        "
            "        "
            "        "
            "        "
            "        ")
    },
    {
        /* [] */
        CHAFA_SYMBOL_TAG_,
        0xf283,
        CHAFA_SYMBOL_OUTLINE_8X8 (
            "        "
            "   X    "
            "   X    "
            "        "
            "        "
            "        "
            "        "
            "        ")
    },
```

As you can see, the cells are mostly empty. FWIW I think the Kreative table may be misrepresenting them by showing them in boxes that are narrower than the other glyphs.

Does that make sense based on what you're seeing? Do other glyphs come through ok?

**Comment by oshaboy** [comment]
I am getting the same problem with all the characters in Kreative Square except the Symbols for Legacy Computing.

**Comment by hpjansson** [comment]
I see. Is your terminal configured to use the same font?

**Comment by oshaboy** [comment]
Yeah if I echo the UTF-8 code manually it works fine.

**Comment by hpjansson** [comment]
Sounds like this is a bit more involved, then. It works on my system, so we need to look for a way to trigger the issue consistently. Could you provide:

- How you installed Chafa (e.g. from package manager, built from source, static binary download...)
- The output from `chafa --version`
- Name and version of your operating system
- Name and version of your terminal emulator
- The bad output from Chafa (preferably redirected to a file and attached here)

**Comment by oshaboy** [comment]
I've installed chafa from the Archlinux package manager

`Chafa version 1.12.4

Loaders:  GIF ImageMagick JPEG PNG SVG TIFF WebP XWD
Features: mmx sse4.1 popcnt
Applying: mmx sse4.1 popcnt

Copyright (C) 2018-2022 Hans Petter Jansson et al.
Incl. libnsgif copyright (C) 2004 Richard Wilson, copyright (C) 2008 Sean Fox
Incl. LodePNG copyright (C) 2005-2018 Lode Vandevenne

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

It's EndeavourOS so there's no version number. 

`GNOME Terminal 3.48.2 using VTE 0.72.2 +BIDI +GNUTLS +ICU +SYSTEMD`

The output is just a bunch of spaces with escape codes It doesn't use any of the PUA characters
[chafa_output.txt](https://github.com/hpjansson/chafa/files/12640823/chafa_output.txt)


At least I know now the problem is with my installation and not chafa.

**Comment by oshaboy** [comment]
Yeah I just compiled chafa from source and it fixed the problem. Thank you for your patience.

**Comment by oshaboy** [comment]
The Legacy Computing Supplement is still broken BTW. I assume it's because they aren't part of Unicode yet.

**Comment by hpjansson** [comment]
Oh, great. No problem.

Legacy is part of Unicode now, and it should work. There's even a class for it, so you can use `chafa --symbols legacy ...`.

**Comment by oshaboy** [comment]
Not Legacy, the Legacy Supplement that's planned for Unicode 16. https://www.unicode.org/L2/L2022/22016.htm#170-C15

**Comment by hpjansson** [comment]
Ah. Yeah, lots of good symbols there, I like the big letter ones too. Too bad they're still \~censoring\~ the Bob Dobbs ones from the Atari ST!

By the way, the most likely reason symbols are being left out is that Chafa by default refuses to use code points that may have an ambiguous width (halfwidth vs fullwidth). Unicode is sort of underspecified for monospace terminals.

You can force it to accept these ranges with `chafa --symbols ambiguous+...`. That will activate every ambiguous range, though, so you may get other symbols in addition to the ranges you specify. You can subtract them from the set, but it's a little tedious: `chafa --symbols ambiguous+f280..f2bf-0..f279-f2c0..fffff` might work. Maybe I'll add logical ops at some point so you could do `chafa --symbols ambiguous&f280..f2bf`.

I looked into it some more, and I suspect the reason it started working when you compiled it from source is [this change](https://github.com/hpjansson/chafa/commit/58f40ca402affaa4c49f04ab05409b18ef1bb8bf) from January.
