### ISSUE TITLE
When sixel format is used with gifs the image "walks" up the screen

### ISSUE THREAD

**Issue by brendenhoffman** [hpjansson/chafa#169]
This is much more easily described with a simple demonstration
![rotate](https://github.com/hpjansson/chafa/assets/13664514/71ce714f-4b17-44ed-b4f6-ea23958375bf)

As you can see, the image is not rendered in place, every frame makes it go up one line. As far as I have seen, this does not happen with kitty or symbols

**Comment by hpjansson** [comment]
Hi, thanks for reporting this. Which version of Chafa are you using, and which terminal? Does it improve if you run it with `chafa --polite off`?

**Comment by brendenhoffman** [comment]
Oops, meant to include my terminal, I am using foot. Chafa version 1.12.4. Nothing seems to change with `--polite off`.

**Comment by hpjansson** [comment]
Are you able to test with the master branch? I've improved the positioning logic, so there's a good chance it's already fixed.

**Comment by brendenhoffman** [comment]
That does indeed fix it. I am running the version currently in the Arch repos. For some reason it didn't move the files out of the git dir when I ran `sudo make install` so I will have to look into that to run the new version, then ideally make a package for 1.13.0

**Comment by hpjansson** [comment]
Glad to hear it's working. I'll release 1.14 soon with the fix, hopefully the distro packages won't take too long.

`sudo make install` should install to `/usr/local` by default, so if it's not first in your search path, the version from `/usr` is likely being picked up instead. If the files aren't being installed at all, that's a bug, and a pretty concerning one at that! We can pursue it in another ticket if you like.

**Comment by brendenhoffman** [comment]
Yes, that was exactly it. Took a bit of head scratching to make the package and I probably (definitely) did some no-nos, but I have it so that it will be updated whenever the Arch maintainers update it, which I wouldn't hold my breath on being soon.
