### ISSUE TITLE
Using layer flags for commands other than layer

### ISSUE THREAD

**Issue by Co3co** [hpjansson/chafa#171]
I want to run `ueberzugpp cmd` with `-o sixel --no-opencv` , but I'm not sure how. Specifying it in the config file only works for `ueberzugpp layer`, and the LF integration scripts use `ueberzugpp cmd`.

**Comment by Co3co** [comment]
This was entirely my fault. I was not using the right lf wrapper.

**Comment by KagoraTheGrindcoreAddict** [comment]
Very cool and awesome issue coco. :+1:

**Comment by hpjansson** [comment]
Hi! Uh. Bye.

(Deleting as requested. Have a nice day!)
