### ISSUE TITLE
Mix between colors using unicode block glyphs

### ISSUE THREAD

**Issue by Lassebq** [hpjansson/chafa#172]
Using block glyphs U+2591 U+2592 and U+2593 (░, ▒ and ▓ ) for non-true color terminals (or even linux console, which only has 16 colors) it could "increase" color palette without actually using more colors.
Sometimes 16 colors is just not enough to make sense out of an image, so using this trick could help a bit.

**Comment by hpjansson** [comment]
Have you tried using `--symbols none --fill space+solid+stipple`?

**Comment by Lassebq** [comment]
Yes, that does work. I didn't know I had to use --fill parameter

**Comment by hpjansson** [comment]
Great! It can be combined with structural symbols, so you don't need `--symbols none` for it to work -- but then you'll only get fill symbols in areas that were left blank by the structural pass.

Chafa has a lot of options now, so maybe we need to write some intro documentation going over the features :-)
