### ISSUE TITLE
Arch package nitpicks

### ISSUE THREAD

**Issue by quincynyan** [hpjansson/chafa#183]
![image](https://github.com/hpjansson/chafa/assets/65074780/3323d250-307a-4cee-96ce-c6bfad60437b)

The pacman release of chafa hasn't been updated to 1.14.0 yet.

**Comment by quincynyan** [comment]
By the way, this is irrelevant to this thread, but I want to reopen #164 as a feature request. I don't want to create another separate issue, as the behavior I want is already described in that issue.

**Comment by hpjansson** [comment]
No problem, I'll reopen. Let's discuss more there.

**Comment by veltza** [comment]
It has already been [updated](https://archlinux.org/packages/extra/x86_64/chafa/).

**Comment by hpjansson** [comment]
Top notch. The only issue I see is that it looks like the ImageMagick is still listed as a dependency. And the description is a little out of date, it should probably say "Terminal graphics rendering toolkit" or something like that.

**Comment by veltza** [comment]
> Top notch. The only issue I see is that it looks like the ImageMagick is still listed as a dependency. And the description is a little out of date, it should probably say "Terminal graphics rendering toolkit" or something like that.

Feel free to inform Felix and don't shoot the messenger.  😉

**Comment by hpjansson** [comment]
Oh, it wasn't directed at anyone in particular, more like a note to self. Thanks for letting us know.

**Comment by Delgan** [comment]
The `imagemagick` dependency was removed in version `1.14.0-3` of the package. :+1:

**Comment by hpjansson** [comment]
Great! I think we can close this now then (thanks, Felix).
