### ISSUE TITLE
Legacy computer symbol support

### ISSUE THREAD

**Issue by hpjansson** [hpjansson/chafa#19]
PETSCII, teletext, etc. When/if this makes it into Unicode, we should support it: https://www.unicode.org/L2/L2017/17435r-terminals-prop.pdf

Mentioned by @kilobyte in https://github.com/hpjansson/chafa/pull/17#issuecomment-421791991.

**Comment by cdluminate** [comment]
The "Block mosaic terminal graphic characters" are 2x3 blocks. With some minor modification my script can generate the corresponding font.

I like the set of "Smooth mosaic terminal graphic characters". They are better candidates for fitting the slant edges.

**Comment by hpjansson** [comment]
Hopefully they would show up in mainstream fonts quite quickly, but a custom font could be used as a stopgap.

**Comment by hpjansson** [comment]
January 2019 version of the proposal: https://www.unicode.org/L2/L2019/19025-terminals-prop.pdf

**Comment by cdluminate** [comment]
Unicode 12.0 was released. The proposal is still not merged.

**Comment by hpjansson** [comment]
Chafa can do this now, with `--glyph-file font.ttf`. Obviously the font must also be active in the terminal for proper display.

Here's one such font: https://style64.org/c64-truetype

However, this bug should remain open until the symbols get official Unicode ranges and we add built-in glyphs for them.

**Comment by kilobyte** [comment]
Merged in Unicode 13.0.

**Comment by hpjansson** [comment]
> Merged in Unicode 13.0.

You beat me to it! The official chart is here: https://www.unicode.org/charts/PDF/Unicode-13.0/U130-1FB00.pdf

To be done: Add a symbol range alias for --symbols and --fill.

**Comment by hpjansson** [comment]
We have builtins and ranges for sextants and smooth mosaic symbols ("wedges") now: `CHAFA_SYMBOL_TAG_SEXTANT` and `CHAFA_SYMBOL_TAG_WEDGE`. On the command line these are `--symbols sextant,wedge`.

Still need to go over it and check that we have all the wedge shapes and see if there are more useful symbols to add (diagonals and checkerboards?).

**Comment by hpjansson** [comment]
I added the remaining useful legacy symbols that had font support on my system (horizontal and vertical lines, diagonals, 180 degree borders, checkerboards, and a few more) to the sextants and wedges already implemented by @hodefoting. See: 0200dd02d5b6f180332a1bfc2944238ccb11beaa, a8c78d2f286dc61893bfd5604eccf32320bc6c81, d11d2ea7ae8f109b67d6e2bb48916dae098a55f3, 80d6b96ef73226cce66464299808dd8e38c97037.

Time to finally close this!
