### ISSUE TITLE
Segfault when doing --symbols on WSLg

### ISSUE THREAD

**Issue by stgiga** [hpjansson/chafa#206]
I'm using WSLg in Windows 11's Terminal with the WSL being Ubuntu 24.04, and I do `chafa -f symbols 0..10ffff --glyph-file UnifontExMono.ttf ` and then the image file [here](http://stgiga.github.io/gigaware/Fancy.png) oh and you can get the TrueType I used [here](http://stgiga.github.io/UnifontEX/UnifontExMono.ttf) but what I'm trying to get chafa to do is render an image in ALL characters in the font. The font doesn't have `Symbols For Legacy Computing` in it, because it's based on Unifont-JP 15.0.06 + Unifont 11.0.01 Upper. It has 65417 glyphs, and they are all assigned. It's a better fallback font than Unifont itself. I used JP because it has more characters, and thus more possible brightness values when used in this fashion. In fact, *almost* 16 bits of brightness. I just want to be able to use ALL the characters in it to make terminal art that is more-realistic. Please fix this. Also Ubuntu is stuck on 1.14.0 of chafa. 

Chafa will segfault if I use --symbols with anything after it.

`--symbols ascii` will work, and `--symbols 3400..9FFF` will work too. It seems that ranges which have any unassigned characters in them will cause an instant segfault.

Also, UnifontEX, unlike regular Unifont, has been specially customized to work in a terminal (among other environments), and be the best terminal font for this type of thing.

**Comment by hpjansson** [comment]
Hi, thanks for reporting this. Are you able to run it under gdb to get a backtrace?

**Comment by hpjansson** [comment]
Never mind, I think I can reproduce this with your font. Interesting!

**Comment by hpjansson** [comment]
The fix will be in 1.14.2. Thanks again.

**Comment by stgiga** [comment]
The issue is still fixed even after upgrading to Unicode 15.1
