### ISSUE TITLE
Chafa no longer showing images on urxvt

### ISSUE THREAD

**Issue by neurofire80** [hpjansson/chafa#207]
Hi, I run Manjaro using i3 as the window manager.
I used to use chafa as the image backend to show a jpg logo on neofetch. 
After a Manjaro update in May, I noticed that the logo stopped showing.
After searching around, I found that neofetch was kind of outdated.. so I thought that was the issue, and I tried fastfetch.
However, the same issue occurred with fastfetch also - where the logo should be, there is just an empty space.
I tried using the w3m backend for neofetch, and that does work, but is not ideal as the image just disappears every time the window is resized. That's why I picked chafa over w3m in the first place.
Anyhow, I tried from the command line:
chafa "path to image"
I also tried turning polite on, but that did nothing.
I tried the same in a different terminal emulator (kitty), and that does show the image. So I'm guessing some compatibility between urxvt and chafa is broken.
The urxvt terminal shows glyphs just fine, as previously. It also shows other unicode characters fine. 
Just wondering if anyone has insights regarding this?

**Comment by hpjansson** [comment]
Thanks for reporting this! I suspect it could be #205. A new release will be coming shortly.

**Comment by hpjansson** [comment]
Never mind, I think I can reproduce this with your font. Interesting!

**Comment by malcos** [comment]
I'm observing a similar behavior with xfce4-terminal and xterm. And I can confirm that [rebuilding the AUR package](https://github.com/hpjansson/chafa/issues/205#issuecomment-2212507279) solves the issue.

**Comment by hpjansson** [comment]
Thanks for testing. I just released version 1.14.2 with the fix.
