### ISSUE TITLE
chafa -f sixels file.jpg >file.six produces empty file

### ISSUE THREAD

**Issue by johnd0e** [hpjansson/chafa#213]
Chafa version 1.14.2, Windows

```
chafa -f sixels file.jpg >file.six
```
At least with some files works ok.
But with some others - delays ~1s and produces empty file

[file.jpg.zip](https://github.com/user-attachments/files/16815414/file.jpg.zip)

**Comment by hpjansson** [comment]
Thanks for filing the report. It could be a duplicate of #210. There's a test build attached there if you'd like to try it.

**Comment by johnd0e** [comment]
```
chafa -f sixels file.jpg >file.six
```
What is interesting - with this file it works ok when executed without output redirection.

But I also have file with which it crashes in both cases.

> There's a test build attached there if you'd like to try it.

Thank you, test build works without problems.

So I am closing the issue as duplicate.
