### ISSUE TITLE
The --font-ratio switch is broken

### ISSUE THREAD

**Issue by hpjansson** [hpjansson/chafa#225]
The `--font-ratio` switch does nothing anymore. I probably broke it when adding support for Windows Terminal default cell dimensions.

@johnd0e mentioned running into it. I will push a fix asap.

**Comment by johnd0e** [comment]
Chafa version 1.14.5

> chafa -f sixels --font-ratio=1/1.5 "filename"

For me non-defauIt values still have no effect.

(And this is weird: as far as I remember I have tested 1.14.5 right after release and that time found no problem...)

**Comment by hpjansson** [comment]
Hmm, it seems to work for me (testing with the master branch). I see two issues, though - first, it won't parse `1/1.5` because it accepts either a single real number, or a fraction composed of two integers (so `1/2` will work, but not `1/2.0`). It notifies of this with an error message, but you could argue it should permit reals in the fraction too.

The second issue is simply that `--font-ratio` is for character art -- sixels emits pixels and doesn't really care about fonts. And the ratio doesn't tell the sixel backend how many pixels there are in each character cell, so it can't be used there. Again you could argue that it should be used as a scaling factor for the cell size -- but that would distort the picture, wouldn't it? Would it actually be useful?

**Comment by johnd0e** [comment]
> Again you could argue that it should be used as a scaling factor for the cell size -- but that would distort the picture, wouldn't it? Would it actually be useful?

Well, I actually try to use it to fix distorted picture.
The original file is ok, but the rendering fails, see #214: it is about Windows Terminal.

**Comment by hpjansson** [comment]
Oh, good point - for terminals with a fixed virtual cell size, it makes sense to be able to scale it by a ratio. I'll make it apply to sixels, more consistent that way too.
