### ISSUE TITLE
No such file error when trying to load a web image

### ISSUE THREAD

**Issue by gand0rf** [hpjansson/chafa#233]
I looked around a bit before posting this, so sorry if I missed something. When I try and run chafa, i get the error stating no such file. Not really sure what it could be.

Command:
```
chafa 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21459-RoPwgrZ32gM3.jpg'
```

Output:
```
chafa: Failed to open 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21459-RoPwgrZ32gM3.jpg': No such file or directory
```

I am on Xubuntu 24. I disabled ufw just to see, but still get the same error. chafa works fine with local images.

**Comment by hpjansson** [comment]
Hi, Chafa stopped being able to load images from the network when I removed the ImageMagick dependency in version 1.14.0. This is a little bit inconvenient, but overall it's a good thing, for the following reasons. It:

- Avoids unexpected behavior. It'd probably be possible to craft something that looked like a file name in a script with escape codes that made it load a resource from the network instead.
- Improves security. We can now drop network privileges on startup on platforms that support it and guarantee that Chafa doesn't access the network at all, ever.
- Aligns more closely with the Unix philosophy of doing one thing and doing it well. Less bloat! And other tools are much better at loading network resources anyway.

On the plus side, I improved stdin support, so you should be able to do this instead:

```
curl 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx21459-RoPwgrZ32gM3.jpg' | chafa
```

If this doesn't work for you, please let me know!
