### ISSUE TITLE
[minor] failed to build on hurd-i386

### ISSUE THREAD

**Issue by cdluminate** [hpjansson/chafa#30]
https://buildd.debian.org/status/fetch.php?pkg=chafa&arch=hurd-i386&ver=1.2.0-1&stamp=1565237724&raw=0

**Comment by hpjansson** [comment]
Thanks for pointing it out! I'll release 1.2.1 in a few days with this fix and maybe others if they're reported.

**Comment by hpjansson** [comment]
1.2.1 is out.
