### ISSUE TITLE
Is there a backstory on the name 

### ISSUE THREAD

**Issue by alexmex90** [hpjansson/chafa#35]
I could not find an answer, I find it curious and funny, in my native dialect of Spanish, "chafa" means "lame" or "crappy". It made me chuckle when I saw it, but I like it! specially since it seems like it is a useful utility to have.

**Comment by hpjansson** [comment]
That's exactly the intention! I used to live in Mexico and picked up this very useful word there. Since ANSI art is a poor approximation of the original image, it fits. And if you need something more serious-sounding, there's the backronym "CHaracter Art Facsimile".

**Comment by hpjansson** [comment]
There's a hint on the home page, right below the logo -- https://hpjansson.org/chafa/

**Comment by alexmex90** [comment]
> There's a hint on the home page, right below the logo -- https://hpjansson.org/chafa/

Oops! I totally missed that! 

> That's exactly the intention! I used to live in Mexico and picked up this very useful word there. Since ANSI art is a poor approximation of the original image, it fits. And if you need something more serious-sounding, there's the backronym "CHaracter Art FAcsimile".

That's completely the opposite of chafa! that is really cool! (or should I say chingón?) keep the great work!
