### ISSUE TITLE
Ubuntu PPA?

### ISSUE THREAD

**Issue by hpjansson** [hpjansson/chafa#36]
Hi @cdluminate , hope you're well.

When I make new releases, people will usually ask for an Ubuntu PPA, so I'm considering setting one up. Is it okay if I base it off your existing packages? This would just be a stopgap for when Ubuntu is shipping older versions, obviously.

**Comment by cdluminate** [comment]
My debian packaging scripts are released under the MIT license so you can use them freely: https://salsa.debian.org/debian/chafa/-/blob/master/debian/copyright#L47-49  Feel free to ask if you have any problem in the details of Debian/Ubuntu packaging.

The situation in China is gradually going well and thanks for your concern. Hope you are well too.

**Comment by hpjansson** [comment]
Thank you! I set up PPA dailies here: https://code.launchpad.net/~hpjansson/+recipe/chafa-daily

Please let me know if you have any comments/would like more control over this. Glad to hear you're well -- I'm doing ok too, and things are more or less under control in Norway so far.

**Comment by cdluminate** [comment]
I saw the commit and it's not recommended to directly include the `debian/` directory under the root or source -- All `debian/` directories contained in the root directory of source tree have to be removed before being uploaded to Debian because that results in conflict.

Using the native `debian/` directory provided by upstream is possible. But that's definitely not a recommended workflow in our case.

Maybe move it to `packaging/debian/` ? Or create a separate branch called, say `debian-pkg` based on the `master`, then we can feel free to rebase it at any time.

**Comment by hpjansson** [comment]
I committed the debian/ dir to a separate branch called ppa. It's not going on the master branch or any of the release branches.

For now I'm keeping that branch on LP only so as not to pollute the GitHub upstream. Would it make things easier for you if we kept a Debian packaging branch here?

Speaking of which -- if you want to, I can add you as maintainer so you can commit directly.

**Comment by hpjansson** [comment]
I settled on the branch name `packaging/ubuntu-ppa` in the end. If you want to keep the Debian branch(es) on github too, feel free to create more branches in the `packaging/` namespace.

**Comment by cdluminate** [comment]
> For now I'm keeping that branch on LP only so as not to pollute the GitHub upstream. Would it make things easier for you if we kept a Debian packaging branch here?

It's great that `debian/` directory won't contaminate the master branch. The most convenient way for my Debian work is to keep my current workflow (based on salsa.debian.org). I accepted the invitation, but I'll ask first before pushing anything.

**Comment by cdluminate** [comment]
I'm updating the packaging files for Debian. Shall I directly push the updates to the ppa branch?

**Comment by hpjansson** [comment]
Go ahead! packaging/ubuntu-ppa has a clean copy of your Debian packaging info, unmodified except for a changelog entry I added to get it packaged as 1.4.0+. You can just delete/replace my entry.

**Comment by hpjansson** [comment]
It's also ok to force push the branch if it gets a cleaner result or saves time.
