### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [hpjansson/chafa#43]
The variable “`interrupted_by_user`” should [use the data type “`sig_atomic_t`”](https://wiki.sei.cmu.edu/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Documentation") (instead of “`gboolean`”).

**Comment by hpjansson** [comment]
Good catch. Thanks for reporting it!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/hpjansson/chafa/commit/890d36c886d708ae4e2fc8ce90b4c2cb4aa0f100 "Use sig_atomic_t for interrupt flag").
