### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [hpjansson/chafa#44]
Would you like to [add more error handling](https://github.com/hpjansson/chafa/blob/890d36c886d708ae4e2fc8ce90b4c2cb4aa0f100/tools/chafa/chafa.c#L1467 "Update candidate: run_magickwand()") for return values from a function like “[fwrite](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fwrite.html "Binary output")”?

**Comment by hpjansson** [comment]
Yes, that would be a good idea. I think that on failure, it should just `goto out;`. This also needs to happen in run_gif().

Tangentially, I'm not too happy with the two main loops. Long term I'd like to refactor this code and move it into its own unit with a player-like API (e.g. `player.c`) that could be called from `chafa.c`. It could use GError to report errors properly.

**Comment by elfring** [comment]
Thanks for [your small source code adjustment](https://github.com/hpjansson/chafa/commit/5d65bb8d6539d1de55d7ce6016fcaba4c31ce965 "Add error handling for stdout writes").

**Comment by hpjansson** [comment]
Anytime 👍
