### ISSUE TITLE
Severe warping, broken -O 2..9

### ISSUE THREAD

**Issue by BasedUser** [hpjansson/chafa#48]
I attempted to use chafa on [this image](https://user-images.githubusercontent.com/21104932/103446609-a01b1e00-4c92-11eb-9e3e-7c94f1111c82.png), but instead I got this:
![image](https://user-images.githubusercontent.com/21104932/103446624-d3f64380-4c92-11eb-9f60-b66802cdce5f.png).

Excerpt from a line produced by `chafa thisImage.png > output.ans`:
```
^[[38;2;110;112;128;48;2;110;112;128m ^[[12b^[[38;2;99;101;115;48;2;74;75;83m
```
My best guess for what's happening in the optimization is you're trying to use the CSI sequence `C` (which wouldn't work for other reasons), but instead chafa uses `b`, which according to `man console_codes`, does not exist.

Chafa version 1.5.0 was used in all of these outputs.

P.S. After replacing all occurences of `b` with `C`:
![image](https://user-images.githubusercontent.com/21104932/103446707-c8574c80-4c93-11eb-9cd0-d85d7d9501f2.png)

**Comment by hpjansson** [comment]
Thanks for reporting this. It's using the `b` (REP) sequence correctly, but terminal support for it isn't as good as I thought it was. I'll have to enable it selectively. The output should look ok with `-O 0` or `-O 1`.

I know XTerm and VTE-based terminals (as of at least a year ago) support it. It's [described here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_) (scroll down a bit).

Going by the reference to `console_codes`, I take it you're using the Linux console?

**Comment by BasedUser** [comment]
> I know XTerm and VTE-based terminals (as of at least a year ago) support it.

That would explain why I couldn't get `b` to work, my terminals (specifically `kitty` and the default `tty`) just don't support it...

> Going by the reference to `console_codes`, I take it you're using the Linux console?

Yep!

**Comment by hpjansson** [comment]
Commit ef970f82b5176bd6221dc073a18eb970889c7917 works around this with default options. I'm going to push a commit that fixes this properly, by detecting the capability so REP is never used even with -O 9 if your terminal does not support it.

**Comment by hpjansson** [comment]
Commit 4a816eaa9f6157bfa6f41a0e8014b68fbef3829b is the proper fix.
