### ISSUE TITLE
[Proposal] Add Support For Piping

### ISSUE THREAD

**Issue by gliggy** [hpjansson/chafa#49]
Could you add support for piping a list of files to open?
Sort of like this perhaps:
![Screenshot from 2021-01-22 14-29-44](https://user-images.githubusercontent.com/7481981/105536415-4cfb2080-5cbe-11eb-971a-ddab2f408f45.png)

**Comment by hpjansson** [comment]
I'd like to add more convenience options, so it's a possibility.

What advantages do you see over e.g. `cat files.txt | xargs chafa`?

**Comment by gliggy** [comment]
I wasn't aware of xargs, but that works. :)
Thank you for telling me about xargs, this will probably help me in the future...

**Comment by hpjansson** [comment]
No problem! Piping might still be useful in some cases -- for instance if `chafa` is invoked as a subprocess with `execve()` and the filenames are being fed in slowly (`xargs` will read as many names as it can before doing anything), or if the list is very, very long and you want to process it all in one invocation (`xargs` is limited by the maximum size of the arguments list).

Thanks for filing the issue, I'll think about it some more.
