### ISSUE TITLE
SIGBUS while loading huge gifs

### ISSUE THREAD

**Issue by HakierGrzonzo** [hpjansson/chafa#50]
While attempting to view a 2gb gif file (youtube-dl > ffmpeg > gif) chafa crashed with following message:

```
fish: “chafa rickroll.gif” terminated by signal SIGBUS (Misaligned address error)
```

Firefox plays this gif without errors.

**Comment by hpjansson** [comment]
Thanks for reporting the issue! You madman.

The embedded libnsgif uses signed 32-bit int offsets into the mmapped file, resulting in any file >= 2GiB being flagged as unreadable. Chafa then falls back to the ImageMagick decoder, which tries to decode the entire file to temp buffers before proceeding. At this point it runs out of memory.

I'm committing a fix to master that makes libnsgif use 64-bit offsets. Please let me know if the problem doesn't go away.
