### ISSUE TITLE
Haiku port fails on 32bit

### ISSUE THREAD

**Issue by Begasus** [hpjansson/chafa#54]
The reported error: `chafa-popcnt.c:45:10: error: unknown type name '__int32_t'; did you mean 'u_int32_t'?` can be fixed with the next solution, would this be ok to create a PR for?

```diff
--- a/chafa/internal/chafa-popcnt.c
+++ b/chafa/internal/chafa-popcnt.c
@@ -23,6 +23,10 @@
 #include "chafa.h"
 #include "internal/chafa-private.h"

+#if defined(__HAIKU__)
+    typedef int32_t __int32_t;
+#endif
+
 gint
 chafa_pop_count_u64_builtin (guint64 v)
 {
```

**Comment by hpjansson** [comment]
Thanks for reporting this.

I think it would be better to just change the instances of `__int32_t` to `guint32`. We already use `guint64` in the 64-bit case. PR is welcome!

**Comment by Begasus** [comment]
Thanks for looking into this, I'll report back later :)

**Comment by Begasus** [comment]
PR created, would be nice if someone on a 32bit system could double-check this? :)

**Comment by cdluminate** [comment]
Successfully built in i386 debian chroot. We can merge that PR.

**Comment by hpjansson** [comment]
Thanks a lot for checking.
