### ISSUE TITLE
Taking EXIF orientation metadata into account when displaying photos

### ISSUE THREAD

**Issue by Flimm** [hpjansson/chafa#63]
Photos can contain EXIF metadata. It can contain "Orientation" metadata, which records the orientation of the camera when the photo was taken. Most software such as browsers and image viewers take that orientation into account when displaying the image.

`chafa` does not seem to take the orientation metadata into account. It displays the image rotated in the wrong way, (that is, not rotated at all), compared to the user's expectations from how the photo is displayed in the file explorer, the browser, and other software.

You can find example images with "Orientation" metadata here: https://github.com/ianare/exif-samples/tree/master/jpg/orientation

**Comment by Flimm** [comment]
I tried compiling the latest version on `master` 18bd723ae0273f27b47b75f3cb99019df90f88bd , and it looks like this version does take EXIF orientation metadata into account. Thank you for your work!

**Comment by hpjansson** [comment]
Glad to hear you got it sorted. It has code to get the correct orientation, so it's supposed to work. Thanks for reporting it anyway -- there are a couple of popular distros that still carry very old packages where it might not be working correctly.
