### ISSUE TITLE
chafa: symbol lookup error: chafa: undefined symbol: chafa_term_info_emit_cursor_up

### ISSUE THREAD

**Issue by SignificantCell2** [hpjansson/chafa#73]
I have cloned the repository on  Ubuntu 20.04.3 and compiled it without any issues. However when I invoke chafa from the terminal I get the following error:

```
$ chafa --version # or any command e.g. chafa myImage.png
chafa: symbol lookup error: chafa: undefined symbol: chafa_term_info_emit_cursor_up
```

Thank you

**Comment by SignificantCell2** [comment]
I have attached below the log output of the commands:
```
./autogen
make
sudo make install
```

[autogen.log](https://github.com/hpjansson/chafa/files/7823760/autogen.log)
[make.log](https://github.com/hpjansson/chafa/files/7823761/make.log)
[sudo_make_install.log](https://github.com/hpjansson/chafa/files/7823762/sudo_make_install.log)

**Comment by hpjansson** [comment]
Thanks for filing the issue. Maybe you're being hit by #32. There are two ways to deal with that:

a) `ldconfig` as root after installing.

or

b) `./autogen.sh --enable-rpath` before building.

The latter used to be enabled by default, but it became an issue for packagers instead, so I had to disable it.

**Comment by SignificantCell2** [comment]
Thank you for your reply. As a beginner I was not sure I understood your reply but managed to get it to work. So anyone encountering the same issue is to run the following command:

```
sudo ldconfig
```

**Comment by hpjansson** [comment]
Glad you solved it :)

To be clear, it's not something users should have to do, but the problem is outside Chafa, so I can't fix it here. Since it's reported frequently, I added a note that shows up after `make install` to hopefully save people some time.
