### ISSUE TITLE
Sixels: Issues in XTerm

### ISSUE THREAD

**Issue by hpjansson** [hpjansson/chafa#74]
Sixel display in `xterm -ti vt340` with XTerm version 368 is broken, as @dankamongmen graciously pointed out in #27. I still don't know what's causing it.

**Comment by dankamongmen** [comment]
this is almost certainly https://github.com/dankamongmen/notcurses/issues/1782 DECSDM

**Comment by hpjansson** [comment]
Hugely helpful and very aptly named issue you've got there. Thanks!

**Comment by klamonte** [comment]
Xterm inverted its DECSDM to be correct in [Patch 369](https://invisible-island.net/xterm/xterm.log.html)

**Comment by hpjansson** [comment]
> Xterm inverted its DECSDM to be correct in [Patch 369](https://invisible-island.net/xterm/xterm.log.html)

Thanks, indeed it works fine in XTerm 370.
