### ISSUE TITLE
apt support for ubuntu bionic?

### ISSUE THREAD

**Issue by CouldBeThis** [hpjansson/chafa#75]
Hello, thank you for making and sharing your project with everybody. 

I am running Ubuntu 18.04 (for hardware reasons). Attempting to add your repo for installing but not able. 

* run in terminal `sudo add-apt-repository ppa:hpjansson/chafa` and the output of that included `Hit:20 http://ppa.launchpad.net/hpjansson/chafa/ubuntu bionic InRelease`

* `sudo apt update` and `sudo apt install chafa` but this reaults in `E: Unable to locate package chafa`

I looked in synaptic, updated again, and I can see the repo but not locate the package.

But when I investigate to [Packages in “Chafa”](https://launchpad.net/~hpjansson/+archive/ubuntu/chafa/+packages) on launchpad, I see

> This PPA currently publishes packages for Impish, Hirsute, Groovy, Focal, Eoan, and Disco. 

So I am thinking my version (bionic) is not available. 

If this is the case then it should be indicated on the download page. 

If I am thinking wrong, and the problem is with me, then I am in the wrong place. :) So let me know and I'll seek support on how to use linux somewhere else.

**Comment by cdluminate** [comment]
The earliest ubuntu release shipping chafa package seems to be focal (20.04) https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=chafa. Maybe you can submit a backport request for ubuntu 18.04, or build the package locally (this might be the shortest path) using the source here: https://salsa.debian.org/debian/chafa . Ubuntu pulls this package from Debian. So that git repo is always the latest packaging repo.

**Comment by hpjansson** [comment]
@CouldBeThis Thanks for bringing it up! I've adjusted the PPA branch on Launchpad, and the Bionic build seems to have succeeded now, so you can try again. Please let us know if it works or not.

The PPA is a pretty low-effort mod of @cdluminate's excellent Debian official packages. Any added mistakes are mine :) I keep it around so the master branch can be tested more easily and for builds against older Ubuntu.

**Comment by CouldBeThis** [comment]
Cool thanks! Got it.
