### ISSUE TITLE
Now Konsole supports graphics

### ISSUE THREAD

**Issue by data-man** [hpjansson/chafa#78]
Good news: Konsole (git) supports sixel, iTerm2 and kitty protocols! :tada: 
Works for me :tm: :
```diff
diff --git a/chafa/chafa-term-db.c b/chafa/chafa-term-db.c
index b5cacee..472215e 100644
--- a/chafa/chafa-term-db.c
+++ b/chafa/chafa-term-db.c
@@ -321,6 +321,11 @@ detect_capabilities (ChafaTermInfo *ti, gchar **envp)
         gfx_seqs = sixel_seqs;
     }

+    if (strcasecmp (term_program, "konsole"))
+    {
+        gfx_seqs = sixel_seqs;
+    }
+
     /* Apple Terminal sets TERM=xterm-256color, and does not support truecolor */
     if (!g_ascii_strcasecmp (term_program, "Apple_Terminal"))
         color_seq_list = color_256_list;
```

**Comment by hpjansson** [comment]
Nice! Is there some way to distinguish the git version from older versions that don't support graphics?

**Comment by hpjansson** [comment]
Also, that should probably be `!g_ascii_strcmp()` instead of `strcasecmp()`.

**Comment by cdluminate** [comment]
According to https://pointieststick.com/2022/02/11/this-week-in-kde-a-smooth-release-of-plasma-5-24/, it requires `konsole >= 22.04`. Debian sid currently has `21.08`, which does not support sixel yet. Maybe we can perform an additional version test.

```
~ ❯❯❯ konsole --version
konsole 21.08.2
```

**Comment by data-man** [comment]
> should probably be !g_ascii_strcasecmp() instead of strcasecmp()

I tried this:
```c
...
if (!g_ascii_strcasecmp (term_program, "konsole"))
{
    gfx_seqs = sixel_seqs;
    printf("In Konsole!\n");
}
...
```
Isn't worked. ;)

**Comment by data-man** [comment]
> it requires konsole >= 22.04

Hmm, `konsole --version` is `konsole 22.03.70` for me. (from [KDE/konsole](https://github.com/KDE/konsole))

**Comment by hpjansson** [comment]
Konsole 21.12.2 sets the env vars `TERM=xterm-256color` and `KONSOLE_VERSION=211202` here. So we may be able to check for KONSOLE_VERSION >= 220400. Is 22.3 a development version?

**Comment by data-man** [comment]
I don't understand why `Konsole` version check is needed?
Just wondering: what happens if `xterm` is compiled without `sixels` support?
E.g. in `Devuan` (at least in `Daedalus/Ceres`) `xterm (v. 370)` doesn't support `sixels` and it's awful.

**Comment by hpjansson** [comment]
The reason is that the feature detection should err on the safe side. I don't think a quality boost for 9/10 users is worth it if it just outputs garbage for the remaining 1/10. People may be using it from backports, static binary, compiled from source on a server that hasn't been updated in a while, etc.

But if we can do a version check, everyone gets what they want. New version, high quality. Old version, symbols only.

We can't detect sixel support reliably in xterm, so everyone gets low quality there, unfortunately. But you can still use `-f sixels`.

**Comment by hpjansson** [comment]
All done starting at Konsole version 22.03.70. Thanks a lot.

**Comment by AutumnMeowMeow** [comment]
I'm looking it konsole now too. Does chafa do anything with DECSDM? It looks like konsole at the moment has the wrong behavior like old xterms.

**Comment by AutumnMeowMeow** [comment]
Also on konsole git head it was reporting 4 (sixel) in DA1.

**Comment by hpjansson** [comment]
Thanks for checking. We're not touching DECSDM. I think it's probably better not to, so the user can configure the output however they want.

Would be nice if konsole defaults were in line with other terminals -- have you filed an issue with them?

**Comment by AutumnMeowMeow** [comment]
We are working through a few things now. 🙂 DECSDM will be fixed, and I think we will also get OSC 4 (query ANSI colors), XTSMGRAPHICS (get number of registers), XTVERSION, and some other glitches fixed.

Also: konsole does iTerm2 and kitty. I'm checking the iTerm2, and notcurses is checking the kitty.

https://gitlab.com/AutumnMeowMeow/jexer/-/issues/113
