### ISSUE TITLE
apt installation guide for Debian testing/unstable user

### ISSUE THREAD

**Issue by cdluminate** [hpjansson/chafa#8]
https://tracker.debian.org/pkg/chafa

Chafa has been available for Debian testing/unstable user for a while. Maybe we can add a hint to readme? like this:

```diff
+# install with apt
+
+ Debian testing/unstable users can install chafa directly with apt.
+
+sudo apt install chafa

 # build from git
 blah blah blah
```

If it looks reasonable, I can fill the wording and submit a PR.

**Comment by hpjansson** [comment]
Absolutely, a PR would be welcome.

**Comment by cdluminate** [comment]
@felixonmars Are you interested in packaging this lovely utility for Archlinux? (no such package in AUR/officlal repo) Chafa is life-saving when a user wants to view an image through ssh without X forwarding. Alternative tools like `catimg` or caca are not as good as this one.

**Comment by cdluminate** [comment]
A good news is that among Debian users who agree to send back installation statistics, more than 500 users have installed chafa: https://qa.debian.org/popcon.php?package=chafa . And the number looks still increasing. In contrast, only 90 have installed catimg https://qa.debian.org/popcon.php?package=catimg and its curve basically converged.

**Comment by hpjansson** [comment]
Looks like a big bump in Feb 2019?

**Comment by cdluminate** [comment]
> Looks like a big bump in Feb 2019?

Yes, this big bump may be associated with the backport work and the freeze process of the next debian release. Chafa is already avaialble for stretch-backports, testing and unstable (aka sid): https://tracker.debian.org/pkg/chafa

**Comment by cdluminate** [comment]
Over 1100 users have installed chafa on their Debian system: https://qa.debian.org/popcon.php?package=chafa .

A new bump happend immediately after the Debian stable release several days ago.

**Comment by hpjansson** [comment]
Awesome. I think we have enough improvements on master to cut a 1.2 release soon, so stay tuned!

**Comment by cdluminate** [comment]
Chafa has become the most popular image viewer in terminal, I think. https://qa.debian.org/popcon.php?package=chafa  Over 2100 debian users installed it.

Seemd that Debian's fontforge had migrated to python3. That means we can start making the chafa8x8 python code python3-only. I think I can do it during the Chinese new year holiday.

**Comment by hpjansson** [comment]
Sounds good! I _may_ release 1.4 sometime in January, but there's nothing preventing another release fairly soon after that. I've already delayed it because the sixel palette mapping is imprecise and I found a better way using Principal Component Analysis that should be both precise and fast. It'll be done Real Soon Now™.

**Comment by cdluminate** [comment]
The installation popularity contest of `chafa` package has passed 10k: https://qa.debian.org/popcon.php?package=chafa

This does not reflect the real number of debian users who installed this package -- the real number must be much higher. And, 10k popcon is already pretty high among debian packages, ranked within top-5%.

**Comment by hpjansson** [comment]
Glorious! :heart:
