### ISSUE TITLE
Chafa --version is returned to stderr, not stdout

### ISSUE THREAD

**Issue by ploum** [hpjansson/chafa#81]
chafa --version returns its output to stderr instead of stdout. 

This looks like a bug to me.

**Comment by hpjansson** [comment]
If you're using this to determine capabilities, you can rely on the following behavior:

- For versions < 1.10, nothing will be printed on stdout.
- For versions >= 1.10, the first line on stdout will be of the form "Chafa version x.y.z".

If you need something more elaborate/machine readable, please let me know.

**Comment by hpjansson** [comment]
(Also yes, rightly considered a bug :)

**Comment by ploum** [comment]
Thanks, that’s indeed easier. I wrote a simpler parser to get the x.y.z but I will remove it in favor of:

if output == '':
   cmd = "chafa --bg white -s %s -w 1 \"%s\"" %(width,img)
else:
   cmd = "chafa --animate=off --bg white -s %s -w 1 \"%s\"" %(width,img)
