### ISSUE TITLE
Margin or centering option when rendering ?

### ISSUE THREAD

**Issue by ploum** [hpjansson/chafa#83]
Unless I’m mistaken, I didn’t find an option to render the picture not on the left of the terminal but with a margin (or centered).

A "margin" option taking a given number of spaces would be perfect for my usecase. (or a "center" option but I feel that "margin" allows centering with simple computation while also allowing more flexibility)

**Comment by hpjansson** [comment]
1.10 will have `--margin-right <n>` and `--margin-bottom <n>`. It would be consistent to add a `--margin-left <n>` too. However, the margin options are really there to accommodate setups that need extra space to avoid scrolling/cursor wrapping, and a `--center` option would be more user friendly (by removing the need for the user to calculate the image dimensions resulting from a scale-to-fit).

Would centering horizontally be sufficient? I suppose centering vertically would be less useful, but it would be possible when combined with `--clear`.

**Comment by ploum** [comment]
On 22/03/16 12:26, Hans Petter Jansson - notifications at github.com wrote:
>1.10 will have `--margin-right <n>` and `--margin-bottom <n>`. It would be consistent to add a `--margin-left <n>` too. However, the margin options are really there to accommodate setups that need extra space to avoid scrolling/cursor wrapping, and a `--center` option would be more user friendly (by removing the need for the user to calculate the image dimensions resulting from a scale-to-fit).
>
>Would centering horizontally be sufficient? I suppose centering 
>vertically would be less useful, but it would be possible when combined 
>with `--clear`.

Indeed, I was only referencing "horizontal centering" (I didn’t ever 
imagined vertical centering).

I realise that --center would be a lot easier as I don’t always know the 
size of the picture. I believe that timg does it right with "-C". By 
default, they don’t upscale so a simple "timg -C picture.png" put the 
image at the original size (or lower if too big), horizontally centered. 
I feed that it’s the more elegant.

**Comment by hpjansson** [comment]
Added `--center on` or `-C on` in 1.10.0, which is out now.
