### ISSUE TITLE
Garbled last row of pixels on some images

### ISSUE THREAD

**Issue by hydrargyrum** [hpjansson/chafa#87]
With this image
![input](https://user-images.githubusercontent.com/2804645/161421563-283fc653-c330-4074-b623-087cd5d43325.png)

    chafa 161421563-283fc653-c330-4074-b623-087cd5d43325.png -s 32x16

I get garbled output on the terminal after last row

![output](https://user-images.githubusercontent.com/2804645/161442430-4150a1fb-bfc1-4617-b1fb-b491c3911ba3.png)

**Comment by hpjansson** [comment]
Hi, thanks for filing the report. Could you provide the output from `chafa --version` and your terminal's name and version? Does the issue go away if you use `chafa --threads 1`?

**Comment by hydrargyrum** [comment]
> Could you provide the output from `chafa --version`

```
Chafa version 1.10.0

Features: mmx sse4.1 popcnt
Applying: mmx sse4.1 popcnt

Copyright (C) 2018-2022 Hans Petter Jansson et al.
Incl. libnsgif copyright (C) 2004 Richard Wilson, copyright (C) 2008 Sean Fox
Incl. LodePNG copyright (C) 2005-2018 Lode Vandevenne

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

> and your terminal's name and version?

terminator and guake (both VTE based) have the same output. xterm (372) has a similar albeit different visual glitch.

> Does the issue go away if you use `chafa --threads 1`?

Indeed.

**Comment by hpjansson** [comment]
Thanks. Did you get it from a binary package (which distro?), or did you build it from source? Which architecture are you on?

**Comment by hydrargyrum** [comment]
A binary package from debian unstable on amd64.

**Comment by hpjansson** [comment]
Fixed. I think I'll need to make a point release for this.

**Comment by cdluminate** [comment]
Will upload the new version to debian upon new point release.

**Comment by hydrargyrum** [comment]
Wow that was all fixed so quickly… thanks a lot!
