### ISSUE TITLE
Invisible SVG

### ISSUE THREAD

**Issue by ploum** [hpjansson/chafa#88]
SVG seems to not be rendered by chafa. I don’t know if they are rendered as black on black or if not rendered at all.

I’v tried multiple backend and playing with --fg /--bg : I still have a black empty space on my terminal.

![mail](https://user-images.githubusercontent.com/1233155/162581650-cf0e033a-d6ac-4596-913d-da7d3437f43e.svg)

**Comment by hpjansson** [comment]
Hmmm. It looks ok here. I get the envelope, a black circle and transparency around the circle. Do you think it could be related to your ImageMagick version or librsvg somehow?

What does `convert bad.svg PNG32:- | chafa` look like?

**Comment by ploum** [comment]
convert-im6.q16: non-conforming drawing primitive definition `' @ error/draw.c/TracePath/6505.
convert-im6.q16: non-conforming drawing primitive definition `path' @ error/draw.c/RenderMVGContent/4404.


then a big white square.

**Comment by ploum** [comment]
Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org

It looks like this version of imagemagick does not handle svg well.

**Comment by ploum** [comment]
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

(in facts, this version does not even claim to support SVG)

**Comment by hpjansson** [comment]
I see. I have ImageMagick 7.1.0 and librsvg 2.50.7 here. That combo seems ok.

**Comment by hpjansson** [comment]
(Come to think of it, I haven't actually checked if ImageMagick uses librsvg, I just sort of assumed it did because librsvg is Quite Good).

**Comment by hpjansson** [comment]
The master branch will build its own SVG loader using librsvg now. It's a lot faster and probably more correct than ImageMagick (when I checked, I discovered IM was spawning an external Inkscape process for rendering -- ouch).

Also, if you have a transparent image and want to composite in on an opaque background, use `--bg <color> -t 1`. The last switch sets the alpha threshold to 1.0 (the maximum), so no transparency makes it past.

**Comment by ploum** [comment]
Thanks for the information, updated offpunk to use that.

**Comment by crmabs** [comment]
C:\prg\bin\Chafa.exe: Failed to open '.\tmp_bigprint.svg': Unknown file format

State of the issue with the latest downloadable executable on windows.
On Jetson Nano  it compiled smooth as usual.
Now on win I got into a little wrestle with the repo when I want to compile it. That's how I bumped into the released .exe
Any pointers building an windows .exe from under wsl?

SVG is the key format :)))) I cannot leave it like this!

**Comment by hpjansson** [comment]
Hey @crmabs, sorry about that. I had to leave out SVG support from the static exes because it was hard to support in a static build. This has probably gotten easier in the past year or two, and I'll revisit it when I have time.

I haven't tried building it in WSL, at least not yet. I usually do cross builds with [MXE](https://github.com/mxe/mxe) because GNU userspace on Windows is too painful :-)

The deal breaker i've run into most frequently on Windows is GNU tools that are built wrong and don't support crlf or non-ascii characters correctly. Have you tried it with MSYS2?

**Comment by hpjansson** [comment]
The other hurdle is that we depend on a post-Rust-rewrite librsvg2. MXE still has the last C-only version, probably because they can't support a Rust toolchain either. I could probably add an option to use an older API there, but old librsvg2 versions don't receive update, so are probably insecure.

**Comment by hpjansson** [comment]
@crmabs I split this off into issue 109 so I don't forget about it. It's better if we keep going there.

**Comment by crmabs** [comment]
Much better when using cygwin. 
keep you informed.
thanks for the efforts!

**Comment by crmabs** [comment]
they all fail, some bit further - and smelling the same - endline madness.  
Slowly we'll get there. 
Chafa from under wsl still supports SVG, so no panic.
