### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [hpjansson/chafa#89]
Hey there!

I belong to an open source security research community, and a member (@jieyongma) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by hpjansson** [comment]
Added the doc. Thanks for reporting it! Let me know if you need anything else.

**Comment by JamieSlome** [comment]
@hpjansson - appreciate your contribution and feedback!

You should have received an e-mail from us about 6 hours ago with further details. You can also view the report directly [here](https://huntr.dev/bounties/104d8c5d-cac5-4baa-9ac9-291ea0bcab95/). It is private and only accessible to you 👍

**Comment by hpjansson** [comment]
I just published [version 1.10.2](https://github.com/hpjansson/chafa/releases/tag/1.10.2) with a fix for @JieyongMa's finding.
